from decimal import *

ZERO = Decimal(0)
ONE = Decimal(1)
ONE_HUNDRED = Decimal(100)

DEFAULT_MONGO_DB_NAME = "crypto-bot"
DEFAULT_MONGO_SELL_ORDERS_COLLECTION = "sell_orders" 
DEFAULT_MONGO_TRADES_COLLECTION = "trades"

AUG_FIRST_TIMESTAMP_MS = 1690891200000