from decimal import *

MAX_PRECISION = 12

ZERO = Decimal(0)
ONE = Decimal(1)
FIVE = Decimal(5)
ONE_HUNDRED = Decimal(100)
QUANTIZING_DECIMAL = ONE.scaleb(-MAX_PRECISION)

DEFAULT_MONGO_DB_NAME = "crypto-bot"
DEFAULT_MONGO_SELL_ORDERS_COLLECTION = "sell_orders" 
DEFAULT_MONGO_TRADES_COLLECTION = "trades"
DEFAULT_MONGO_SNAPSHOTS_COLLECTION = "snapshots"
DEFAULT_MONGO_OHLCV_DATA_COLLECTION = "ohlcv_data"
DEFAULT_MONGO_OHLCV_DATA_GRANULARITY = "minutes"
DEFAULT_MONGO_OHLCV_DATA_META_FIELD = "ticker"
DEFAULT_MONGO_OHLCV_DATA_TIME_FIELD = "timestamp"


DEFAULT_TAKE_PROFIT_THRESHOLD = 2
DEFAULT_TAKE_PROFIT_EVALUATION_TYPE = "AVERAGE"

AUG_FIRST_TIMESTAMP_MS = 1690891200000

CONFIG_OVERRIDES = "overrides"

CONFIG_AMOUNT_PER_TRANSACTION = "amount_per_transaction"
CONFIG_REINVESTMENT_PERCENT = "reinvestment_percent"
CONFIG_TRADE_COOLDOWN_PERIOD = "trade_cooldown_period"
CONFIG_TAKE_PROFITS = "take_profits"
CONFIG_TAKE_PROFITS_THRESHOLD_PERCENT = "threshold_percent"
CONFIG_TAKE_PROFITS_EVALUATION_TYPE = "evaluation_type"
CONFIG_STRATEGIES = "strategies"

CONFIG_STRATEGY_PRIORITY = "priority"
CONFIG_STRATEGY_NAME = "name"
CONFIG_MAX_SPEND = "max_spend"
CONFIG_NAME = "name"
CONFIG_PARAMETERS = "parameters"
CONFIG_ENABLED = "enabled"
CONFIG_CURRENCIES = "currency"
CONFIG_SUPPORTED_CRYPTO_CURRENCIES = "supported_crypto_currencies"
CONFIG_BLACKLISTED_CRYPTO_CURRENCIES = "blacklisted_crypto_currencies"
CONFIG_DRY_RUN = "dry_run"
CONFIG_CURRENCY = "currency"
CONFIG_SLEEP_INTERVAL = "sleep_interval"
CONFIG_INTER_CURRENCY_SLEEP_INTERVAL = "inter_currency_sleep_interval"
CONFIG_DB = "db"
CONFIG_DB_TYPE = "db_type"
CONFIG_DB_NAME = "db_name"
CONFIG_DB_CURRENT_POSITIONS_COLLECTION = "current_positions_collection"
CONFIG_DB_CLOSED_POSITIONS_COLLECTION = "closed_positions_collection"
CONFIG_EXCHANGE = "exchange"
CONFIG_TICKERS = "tickers"

CONFIG_OVERRIDEABLE_ATTRIBUTES = [
    CONFIG_AMOUNT_PER_TRANSACTION,
    CONFIG_REINVESTMENT_PERCENT,
    CONFIG_TRADE_COOLDOWN_PERIOD,
    CONFIG_TAKE_PROFITS
]